### ISSUE TITLE
Error on LMS logs

### ISSUE THREAD

**Issue by robbrad** [molobrakos/docker#1]
Error when starting the container:

Can't open /var/log/squeezeboxserver/server.log (Permission denied) at /usr/share/squeezeboxserver/CPAN/Log/Log4perl/Appender/File.pm line 103.

**Comment by robbrad** [comment]
No worries - I think I did. I did just start it though and publish all all ports using portainer 

Is there some other parameters I need to try

Thanks
Rob

**Comment by molobrakos** [comment]
Just the volume mappings for: /config /music /logs /cache and then any command line option supported by lms.

**Comment by robbrad** [comment]
Mappings are there, but still can’t start it

This is the full error I got

dirsFor: Didn't find a match request: [scprefs]

Can't open /logs/server.log (Permission denied) at /usr/share/squeezeboxserver/CPAN/Log/Log4perl/Appender/File.pm line 103.
